# Generated by Django 3.0.3 on 2021-04-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StuRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_Fnm', models.CharField(max_length=200)),
                ('stu_Lnm', models.CharField(max_length=200)),
                ('stu_cls', models.CharField(max_length=20)),
                ('stu_add', models.TextField()),
                ('stu_mob', models.IntegerField()),
            ],
        ),
    ]
